# Development Podman Compose - pulls images from registries
# Use this for local development before air-gap deployment

version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: rag-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-rag}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rag_password}
      POSTGRES_DB: ${POSTGRES_DB:-ragdb}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag -d ragdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: rag-ollama
    # For Podman with NVIDIA, use CDI
    devices:
      - nvidia.com/gpu=all
    environment:
      OLLAMA_HOST: 0.0.0.0
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 10
    restart: unless-stopped

  # Model initialization - pulls models on first run
  ollama-init:
    image: curlimages/curl:latest
    container_name: rag-ollama-init
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Pulling nomic-embed-text..."
        curl -X POST http://ollama:11434/api/pull -d '{"name": "nomic-embed-text"}'
        echo ""
        echo "Pulling mistral:7b..."
        curl -X POST http://ollama:11434/api/pull -d '{"name": "mistral:7b"}'
        echo ""
        echo "Pulling gpt-oss:20b..."
        curl -X POST http://ollama:11434/api/pull -d '{"name": "gpt-oss:20b"}'
        echo ""
        echo "Models ready!"
    restart: "no"

  api:
    build:
      context: ..
      dockerfile: containers/Containerfile.app
    container_name: rag-api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=postgresql://rag:rag_password@postgres:5432/ragdb
      - OLLAMA_HOST=http://ollama:11434
      - EMBEDDING_MODEL=nomic-embed-text
      - LLM_MODEL=mistral:7b  # Use gpt-oss:20b for production
    volumes:
      - ../app:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  streamlit:
    build:
      context: ..
      dockerfile: containers/Containerfile.app
    container_name: rag-streamlit
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - ../app:/app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - api
    restart: unless-stopped

volumes:
  pgdata:
  ollama_data:

networks:
  default:
    name: rag-network
