# Development Podman Compose - pulls images from registries
# Use this for local development before air-gap deployment

version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: rag-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-rag}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rag_password}
      POSTGRES_DB: ${POSTGRES_DB:-ragdb}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag -d ragdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  ollama:
    image: ollama/ollama:0.1.23
    container_name: rag-ollama
    # For Podman with NVIDIA, use CDI
    devices:
      - nvidia.com/gpu=all
    environment:
      OLLAMA_HOST: 0.0.0.0
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      start_period: 120s
      retries: 5
    restart: unless-stopped

  # Model initialization - pulls models on first run
  ollama-init:
    image: ollama/ollama:0.1.23
    container_name: rag-ollama-init
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      OLLAMA_HOST: http://ollama:11434
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Pulling embedding model..."
        ollama pull nomic-embed-text
        echo "Pulling LLM model..."
        ollama pull gpt-oss:20b
        echo "Models ready!"
    restart: "no"

  api:
    build:
      context: ..
      dockerfile: containers/Containerfile.app
    container_name: rag-api
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-rag}:${POSTGRES_PASSWORD:-rag_password}@postgres:5432/${POSTGRES_DB:-ragdb}
      OLLAMA_HOST: http://ollama:11434
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-nomic-embed-text}
      LLM_MODEL: ${LLM_MODEL:-gpt-oss:20b}
      CHUNK_SIZE: ${CHUNK_SIZE:-512}
      CHUNK_OVERLAP: ${CHUNK_OVERLAP:-50}
      TOP_K_RETRIEVAL: ${TOP_K_RETRIEVAL:-20}
      TOP_K_RERANK: ${TOP_K_RERANK:-5}
    volumes:
      - ../app:/app:ro
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
    restart: unless-stopped

  streamlit:
    build:
      context: ..
      dockerfile: containers/Containerfile.app
    container_name: rag-streamlit
    command: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    environment:
      API_URL: http://api:8000
    volumes:
      - ../app:/app:ro
    ports:
      - "8501:8501"
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  pgdata:
  ollama_data:
