# Development Podman Compose - pulls images from registries
# Use this for local development before air-gap deployment

version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: rag-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-rag}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rag_password}
      POSTGRES_DB: ${POSTGRES_DB:-ragdb}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag -d ragdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  vllm:
    image: vllm/vllm-openai:latest
    container_name: rag-vllm
    # For Podman with NVIDIA, use CDI
    devices:
      - nvidia.com/gpu=all
    volumes:
      - vllm_models:/models
    ports:
      - "8000:8000"
    command: ["--model", "/models/gpt-oss-20b-awq", "--load-format", "awq", "--served-model-name", "gpt-oss:20b", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 120s
      retries: 10
    restart: unless-stopped

  vllm-mistral:
    image: vllm/vllm-openai:latest
    container_name: rag-vllm-mistral
    devices:
      - nvidia.com/gpu=all
    volumes:
      - vllm_models:/models
    ports:
      - "8002:8000"
    command: ["--model", "/models/mistral-7b-awq", "--load-format", "awq", "--served-model-name", "mistral:7b", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 120s
      retries: 10
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: containers/Containerfile.app
    container_name: rag-api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=postgresql://rag:rag_password@postgres:5432/ragdb
      - VLLM_HOST=http://vllm:8000
      - VLLM_MODEL_HOSTS=mistral:7b=http://vllm-mistral:8000
      - EMBEDDING_MODEL=nomic-embed-text
      - LLM_MODEL=gpt-oss:20b
    volumes:
      - ../app:/app
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
      vllm:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  streamlit:
    build:
      context: ..
      dockerfile: containers/Containerfile.app
    container_name: rag-streamlit
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - ../app:/app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

volumes:
  pgdata:
  vllm_models:

networks:
  default:
    name: rag-network
